### ISSUE TITLE
Setup eigr.io documentation

### ISSUE THREAD

**Issue by marcellanz** [eigr/eigr-community#6]
Based on https://github.com/eigr/eigr-community/discussions/5

- [x] register domain
- [x] setup static site
- [x] 1st try with probably docsy
- [x] use GH actions for "deployment"
- [ ] ~logo and colors~

**Comment by marcellanz** [comment]
setup: https://github.com/eigr/eigr.github.io
deployed: https://eigr.github.io

**Comment by sleipnir** [comment]
Great work @marcellanz
